name: Training Pipeline (daily)

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests pandas numpy python-dotenv hopsworks==4.7.* pyarrow confluent-kafka scikit-learn xgboost joblib tensorflow

      - name: Run training pipeline
        run: python pipelines/training_pipeline.py
        env:
          AQICN_TOKEN: ${{ secrets.AQICN_TOKEN }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          HOPSWORKS_PROJECT: ${{ secrets.HOPSWORKS_PROJECT }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}